moduleCooldownProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 90000
    - 60000
moduleAmmunitionProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1
    - 1
moduleEffectMinDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 700
    - 1050
moduleEffectMaxDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1000
    - 1500
moduleEffectImpactProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 3.00
    - 4.50
moduleMineEffectHideRangeProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 25.00
    - 17.00
moduleMineEffectBeginHideDistanceProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 25.00
    - 17.00
moduleEffectActivationTimeProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 3000
    - 2000
moduleLimitBundleEffectCountProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1
    - 1
moduleEffectAccelerationProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 12.00
    - 18.00
moduleEffectSpeedProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 12.00
    - 18.00
moduleSpiderMineEffectEnergyProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 120
    - 120
moduleSpiderMineEffectIdleEnergyDrainRateProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1
    - 1
moduleSpiderMineEffectChasingEnergyDrainRateProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10
    - 10
moduleMineEffectSplashDamageMaxRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 5.00
    - 7.50
moduleMineEffectSplashDamageMinRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10.00
    - 15.00
moduleEffectSplashDamageMinPercentProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.50
    - 0.75
moduleEffectTargetingDistanceProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 15.00
    - 22.50
moduleEffectTargetingPeriodProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.5
    - 0.5
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 90
        - 60
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Damage
      linearInterpolation: true
      upgradeLevel2Values:
        - 700
        - 1050
      maxAndMinString:
        - 700-1000
        - 739-1056
        - 778-1111
        - 817-1167
        - 856-1222
        - 894-1278
        - 933-1333
        - 972-1388
        - 1011-1444
        - 1050-1500
      unit: hp
      maxAndMin: true
      format: 0
      spriteUID: 5538887f-b208-4fb4-ac4a-12223cb09fd3
    - name: VisibilityArea
      linearInterpolation: true
      upgradeLevel2Values:
        - 25
        - 17
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: ActivationTime
      linearInterpolation: true
      upgradeLevel2Values:
        - 3
        - 2
      unit: sec
      format: 0.00
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: ExplosionRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 10
        - 15
      unit: m
      format: 0.0
      spriteUID: c1a7c983-c17f-4f35-8514-8a6bc28fb93b
    - name: "Impact"
      linearInterpolation: true
      upgradeLevel2Values:
        - 3
        - 4.5
      unit: hp
      format: 0.0
      spriteUID: 8bf5d2cc-2f2b-4f2a-8d6e-880bcdbf4844
    - name: TargetingRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 15
        - 22.5
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: Speed
      linearInterpolation: true
      upgradeLevel2Values:
        - 12
        - 18
      unit: meters_per_sec
      format: 0.0
      spriteUID: 88babefa-ef53-4242-bfab-e5a7c7c7fb21
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
