moduleCooldownProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 50000
    - 33333
moduleAmmunitionProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 2
    - 2
moduleEffectMinDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 500.00
    - 750.00
moduleEffectMaxDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1000.00
    - 1500.00
moduleEffectImpactProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 3.00
    - 4.50
moduleMineEffectHideRangeProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10.00
    - 1.00
moduleMineEffectBeginHideDistanceProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10.00
    - 1.00
moduleEffectActivationTimeProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 2000
    - 1333
moduleMineEffectSplashDamageMaxRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 2.00
    - 3.00
moduleMineEffectSplashDamageMinRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 5.00
    - 7.50
moduleEffectSplashDamageMinPercentProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.50
    - 0.75
moduleMineEffectTriggeringAreaProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1.00
    - 1.50
moduleMineEffectExplosionDelayMSProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 2000
    - 1333
moduleLimitBundleEffectCountProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 4
    - 4
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 50
        - 33.3
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Damage
      linearInterpolation: true
      upgradeLevel2Values:
        - 500
        - 750
      maxAndMinString:
        - 500-1000
        - 528-1056
        - 556-1111
        - 583-1167
        - 611-1222
        - 639-1278
        - 667-1333
        - 694-1388
        - 722-1444
        - 750-1500
      unit: hp
      maxAndMin: true
      format: 0
      spriteUID: 5538887f-b208-4fb4-ac4a-12223cb09fd3
    - name: TriggerRadius
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1.5
      unit: m
      format: 0.00
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: VisibilityArea
      linearInterpolation: true
      upgradeLevel2Values:
        - 10
        - 1
      unit: m
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: TriggerDelay
      linearInterpolation: true
      upgradeLevel2Values:
        - 2
        - 1.33
      unit: sec
      format: 0.00
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: ActivationTime
      linearInterpolation: true
      upgradeLevel2Values:
        - 2
        - 1.33
      unit: sec
      format: 0.00
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: ExplosionRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 5
        - 7.5
      unit: m
      format: 0.0
      spriteUID: c1a7c983-c17f-4f35-8514-8a6bc28fb93b
    - name: "Impact"
      linearInterpolation: true
      upgradeLevel2Values:
        - 3
        - 4.5
      unit: hp
      format: 0.0
      spriteUID: 8bf5d2cc-2f2b-4f2a-8d6e-880bcdbf4844
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 2
        - 2
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
