moduleCooldownProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 81000
    - 78000
    - 75000
    - 72000
    - 69000
    - 66000
    - 63000
    - 60000
    - 57000
    - 54000
moduleAmmunitionProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
moduleEffectDurationProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 4000
    - 4000
    - 4000
    - 5000
    - 5000
    - 5000
    - 5000
    - 6000
    - 6000
    - 6000
moduleHealingEffectInstantHPProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 500
    - 528
    - 556
    - 583
    - 611
    - 639
    - 667
    - 694
    - 722
    - 750
moduleHealingEffectHPPerMSProperty:
  linearInterpolation: false
  upgradeLevel2Values:
    - 0.08
    - 0.08
    - 0.09
    - 0.09
    - 0.10
    - 0.10
    - 0.11
    - 0.11
    - 0.12
    - 0.12
...
