moduleCooldownProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 80000
    - 53333
moduleAmmunitionProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1
    - 1
moduleEffectImpactProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.00
    - 0.00
moduleEffectSplashRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10.00
    - 15.00
moduleEffectSplashDamageMinPercentProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.50
    - 0.75
moduleFireRingEffectHeatDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 150
    - 225
moduleEffectTemperatureDeltaProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1.00
    - 1.00
moduleEffectTemperatureLimitProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.60
    - 0.90
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 80
        - 53.3
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: TargetingRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 10
        - 15
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: HeatTemperatureLimit
      linearInterpolation: true
      upgradeLevel2Values:
        - 60
        - 90
      format: 0
      unit: percent
      spriteUID: 80bffee2-17be-4764-8c1d-8d45cede10ff
    - name: HeatDamage
      linearInterpolation: true
      upgradeLevel2Values:
        - 150
        - 225
      format: 0
      unit: hp
      spriteUID: 80bffee2-17be-4764-8c1d-8d45cede10ff
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 1
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
