idleKickConfig:
  idleKickTimeSec: 120
  idleWarningTimeSec: 60
  checkPeriodicTimeSec: 10
upsideDownConfig:
  upsideDownAngleToNormal: 110
  detectionPauseSec: 6
  maxRankForMessage: 6
selfDestructionConfig:
  suicideDurationTime: 5
reservationConfig:
  reservationDurationTimeSec: 120
userDowngradeConfig:
  downgradeXPRatio: 0.33
