moduleCooldownProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 60000
    - 40000
moduleAmmunitionProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 2
    - 2
moduleEffectMinDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 300.00
    - 450.00
moduleEffectMaxDamageProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 600.00
    - 900.00
moduleEffectImpactProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.00
    - 0.00
moduleMineEffectHideRangeProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10.00
    - 5.00
moduleMineEffectBeginHideDistanceProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 10.00
    - 5.00
moduleEffectActivationTimeProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1000
    - 667
moduleMineEffectSplashDamageMaxRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 2.00
    - 3.00
moduleMineEffectSplashDamageMinRadiusProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 8.00
    - 12.00
moduleEffectSplashDamageMinPercentProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 0.50
    - 0.75
moduleMineEffectTriggeringAreaProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 3.00
    - 4.50
moduleMineEffectExplosionDelayMSProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 1000
    - 667
moduleLimitBundleEffectCountProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 3
    - 3
moduleIcetrapEffectTemperatureDurationProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - 6000
    - 9000
moduleEffectTemperatureDeltaProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - -0.30
    - -0.45
moduleEffectTemperatureLimitProperty:
  linearInterpolation: true
  upgradeLevel2Values:
    - -0.70
    - -1.00
moduleVisualProperties:
  properties:
    - name: Cooldown
      linearInterpolation: true
      upgradeLevel2Values:
        - 60
        - 40
      unit: sec
      format: 0.0
      spriteUID: 75703cb6-f734-4a53-9b7b-fcb5df984159
    - name: Damage
      linearInterpolation: true
      upgradeLevel2Values:
        - 300.00
        - 450.00
      maxAndMinString:
        - 300-600
        - 316-633
        - 333-666
        - 350-700
        - 366-733
        - 383-766
        - 400-800
        - 416-833
        - 433-866
        - 450-900
      unit: hp
      format: 0.0
      maxAndMin: true
      spriteUID: bdaa35da-f24c-4dc5-a4e2-050c31e328f9
    - name: TriggerRadius
      linearInterpolation: true
      upgradeLevel2Values:
        - 3
        - 4.5
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: VisibilityArea
      linearInterpolation: true
      upgradeLevel2Values:
        - 10
        - 5
      unit: m
      format: 0.0
      spriteUID: 41de9e99-f59b-446b-a2df-5be14c0c80d3
    - name: TriggerDelay
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 0.67
      unit: sec
      format: 0.00
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: ActivationTime
      linearInterpolation: true
      upgradeLevel2Values:
        - 1
        - 0.67
      unit: sec
      format: 0.00
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: ExplosionRange
      linearInterpolation: true
      upgradeLevel2Values:
        - 8
        - 12
      unit: m
      format: 0.0
      spriteUID: c1a7c983-c17f-4f35-8514-8a6bc28fb93b
    - name: TemperatureDuration
      linearInterpolation: true
      upgradeLevel2Values:
        - 6
        - 9
      unit: sec
      format: 0.0
      spriteUID: b96547e2-3a61-4cc9-b494-29dc48eea542
    - name: FreezeTemperatureLimit
      linearInterpolation: true
      upgradeLevel2Values:
        - 70
        - 100
      format: 0
      unit: percent
      spriteUID: af08ec8b-605b-4617-9ba1-e371abdf885b
    - name: FreezeTemperatureDelta
      linearInterpolation: true
      upgradeLevel2Values:
        - 30
        - 45
      format: 0
      unit: percentinsec
      spriteUID: af08ec8b-605b-4617-9ba1-e371abdf885b
    - name: Reserve
      linearInterpolation: true
      upgradeLevel2Values:
        - 2
        - 2
      format: 0
      spriteUID: 85ecaf68-fb3d-4cec-b8a9-e2b5b6cf8602
...
