---
descriptionItem:
  name: "Quick Play"
  description: "The fastest battle search! Compete with other players in random mode and on a random map."
# description: "Fight on virtual battlefields for teleport charges. Quick play is the best way to improve your skills for ranking battles and of course to have fun!"