host: *ip*
acceptorPort: 5050
configVersion: Vint-8
bundleDbVersion: Vint-8
resourcesUrl: http://*host*/resources
configsUrl: http://*host*/config
updateConfigUrl: http://*host*/update/{BuildTarget}.yml
stateFileUrl: http://*host*/state/_state.yml
